// GENERATED by `node worker/bundle.js` from calls.js, worker/feed-core.js and worker/index.mjs. Do not edit.
const Calls = (function () { const module = { exports: {} }; 
// Call queue: pure helpers (no DOM, no network). Pull contract addresses and posters out of Discord text
// or Discord API messages, keep one queue entry per coin, rank by safety and age, and score callers.
// Used by the app and by the Discord feed Worker.
(function (root) {
  'use strict';
  const B58 = '1-9A-HJ-NP-Za-km-z';
  const ADDR = new RegExp(`(0x[0-9a-fA-F]{40})(?![0-9a-fA-F])|(?<![${B58}])([${B58}]{32,44})(?![${B58}])`, 'g');
  const IGNORE = new Set([
    'So11111111111111111111111111111111111111112', 'So11111111111111111111111111111111111111111', // SOL
    'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v', 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB', // USDC, USDT
  ]);
  // "name — Today at 2:41 PM", "name — 10/08/2026 2:41 PM", "name — Yesterday at …"
  const HEADER = /^(.{1,40}?)\s+[—–-]\s+(Today at|Yesterday at|\d{1,2}\/\d{1,2}\/\d{2,4}|[A-Z][a-z]+ \d{1,2},? \d{4})/;
  // "[3:04 PM] name: message"
  const BRACKET = /^\[[^\]]{3,20}\]\s*([^:]{1,40}):\s*(.*)$/;

  function addressesIn(text) {
    const out = [];
    for (const m of String(text || '').matchAll(ADDR)) {
      if (m[1]) out.push({ address: m[1].toLowerCase(), chain: 'evm' });
      else if (m[2] && !IGNORE.has(m[2])) out.push({ address: m[2], chain: 'solana' });
    }
    return out;
  }

  // Pasted or shared text, e.g. a copied run of Discord messages.
  function extractCalls(text, now) {
    const calls = [];
    let poster = 'unknown';
    for (const raw of String(text || '').split(/\r?\n/)) {
      const line = raw.trim();
      if (!line) continue;
      const h = line.match(HEADER);
      if (h && !addressesIn(line).length) { poster = h[1].trim(); continue; }
      const b = line.match(BRACKET);
      const who = b ? b[1].trim() : poster;
      for (const a of addressesIn(b ? b[2] : line)) calls.push(Object.assign(a, { poster: who, at: now }));
    }
    return calls;
  }

  const snowflakeCmp = (a, b) => (a.length - b.length) || (a < b ? -1 : a > b ? 1 : 0);

  // ---- alert bot messages (market snapshot embed + "Last mentions" / "First scan" embed) ----
  const MEDALS = { '🥇': 'gold', '🥈': 'silver', '🥉': 'bronze', '🌱': 'new' };
  const KMB = { K: 1e3, M: 1e6, B: 1e9 };
  const num = (t) => {
    const m = String(t == null ? '' : t).trim().replace(/,/g, '').match(/^([\d.]+)\s*([KMB])?$/i);
    return m ? Number(m[1]) * (m[2] ? KMB[m[2].toUpperCase()] : 1) : null;
  };
  const AGE_UNIT = { m: 60000, h: 3600000, d: 86400000 };
  const ageMs = (t) => { const m = String(t || '').trim().match(/^(\d+(?:\.\d+)?)\s*([mhd])$/i); return m ? Number(m[1]) * AGE_UNIT[m[2].toLowerCase()] : null; };
  const HEAD = /^\*\*\[([^\]]+)\]\([^)]*\)\s*\[([^/\]]+)\/([^\]]*)\]\s*-\s*([^*]+?)\*\*/;
  const MENTION = /^\**\s*(→\s*)?<t:(\d+):[A-Za-z]>\s*[⋅·]\s*(?:<a?:[^>]+>\s*)?(\S{1,8})\s*[⋅·]\s*\[([^\]]+)\]\([^)]*\)\s*@\s*([\d.,]+\s*[KMBkmb]?)\**\s*(?:[⋅·]\s*(🥇|🥈|🥉|🌱)\s*(?:[⋅·]\s*(\d+(?:\.\d+)?)%\s*[⋅·]\s*(\d+)d)?)?/u;
  const STATS = /(🥇|🥈|🥉|🌱)?\s*[⋅·]?\s*[\d.]+x\+\s*hits:\s*\**(\d+(?:\.\d+)?)%\**\s*7d\s*[⋅·]\s*\**(\d+(?:\.\d+)?)%\**\s*30d\s*\((\d+)\s*calls\)\s*[⋅·]\s*30d median\s*\**([\d.]+)x/u;
  const tick = (d, label) => { const m = d.match(new RegExp(label + ':\\s*`([^`]+)`')); return m ? m[1] : null; };

  // One alert -> { address, chain, name, symbol, snap, trigger, first, mentions } or null when it is not an alert.
  function parseAlert(m) {
    const embeds = (m && m.embeds) || [];
    const market = embeds.map((e) => e.description || '').find((d) => /FDV:/.test(d) && /Liq:/.test(d));
    if (!market) return null;
    const ca = market.match(/^`([^`\s]{32,44})`\s*$/m);
    const addr = ca && addressesIn(ca[1])[0];
    if (!addr) return null;
    const head = String(m.content || '').match(HEAD);
    const one = market.match(/1H:\s*`([-+\d.,]+)%?`\s*\S+\s*`([^`]+)`\s*\S+\s*`([^`]+)`/u);
    const th = market.match(/TH:([^\n]*)/);
    const top5 = th ? [...th[1].matchAll(/\[(\d+(?:\.\d+)?)\]\(/g)].map((x) => Number(x[1])) : [];
    const top5Pct = th ? (th[1].match(/`\[(\d+(?:\.\d+)?)%\]`/) || [])[1] : undefined;
    const snap = {
      priceUsd: Number((market.match(/USD:\s*`([\d.eE+-]+)`/) || [])[1]) || null,
      fdv: num(tick(market, 'FDV')), liq: num(tick(market, 'Liq')), vol: num(tick(market, 'Vol')), ageMs: ageMs(tick(market, 'Age')),
      change1h: one ? Number(one[1].replace(/,/g, '')) : null, buys: one ? num(one[2]) : null, sells: one ? num(one[3]) : null,
      holders: num(tick(market, 'Total')), top5, top5Pct: top5Pct === undefined ? null : Number(top5Pct),
    };
    const detail = embeds.map((e) => e.description || '').find((d) => /Last mentions|First scan/.test(d)) || '';
    /** @type {any[]} */
    const mentions = [];
    for (const line of detail.split(/\r?\n/)) {
      const x = line.trim().match(MENTION);
      if (!x) continue;
      mentions.push({ arrow: !!x[1], ts: Number(x[2]) * 1000, group: x[3], caller: x[4], mcap: num(x[5].replace(/\s+/g, '')), medal: x[6] ? MEDALS[x[6]] : null, winRate: x[7] === undefined ? null : Number(x[7]), window: x[8] ? Number(x[8]) : null });
    }
    const st = detail.match(STATS);
    const trigger = mentions.find((x) => x.arrow) || mentions[0] || null;
    if (trigger && st) {
      trigger.stats = { medal: st[1] ? MEDALS[st[1]] : null, hit7: Number(st[2]), hit30: Number(st[3]), calls30: Number(st[4]), median: Number(st[5]) };
      trigger.winRate = trigger.stats.hit30;
      if (trigger.stats.medal) trigger.medal = trigger.stats.medal;
    }
    const first = mentions.length ? mentions.reduce((a, b) => (b.ts < a.ts ? b : a)) : null;
    return { address: addr.address, chain: addr.chain, name: head ? head[1] : '', symbol: head ? head[4].split('/')[0].trim() : '', snap, trigger, first, mentions };
  }

  // Caller profile updates from alert messages: every mention line is a fresh look at that caller's record.
  function callerUpdates(messages) {
    const out = [];
    for (const m of messages || []) {
      const a = parseAlert(m);
      if (!a) continue;
      for (const x of a.mentions) {
        const u = { caller: x.caller, group: x.group, medal: x.medal, winRate: x.winRate, ts: x.ts };
        if (x.stats) Object.assign(u, { hit7: x.stats.hit7, calls30: x.stats.calls30, median: x.stats.median });
        out.push(u);
      }
    }
    return out;
  }

  // profiles: { lowercase name: { name, group, medal, winRate, hit7, calls30, median, calls, updatedAt, lastTs } }.
  // The newest sighting wins; a mention already counted (same or older time) changes nothing; "no data" never erases a rate.
  function applyCallerUpdates(profiles, updates, max = 3000) {
    const out = Object.assign({}, profiles);
    for (const u of (updates || []).slice().sort((a, b) => a.ts - b.ts)) {
      const key = String(u.caller).toLowerCase();
      const cur = out[key];
      if (!cur) {
        out[key] = { name: u.caller, group: u.group || '', medal: u.medal || 'new', winRate: u.winRate == null ? null : u.winRate, hit7: u.hit7 == null ? null : u.hit7, calls30: u.calls30 == null ? null : u.calls30, median: u.median == null ? null : u.median, calls: 1, updatedAt: u.ts, lastTs: u.ts };
        continue;
      }
      if (!(u.ts > cur.lastTs)) continue;
      const next = Object.assign({}, cur, { name: u.caller, group: u.group || cur.group, calls: cur.calls + 1, lastTs: u.ts, updatedAt: u.ts });
      if (u.winRate != null) { next.winRate = u.winRate; next.medal = u.medal || cur.medal; }
      else if (u.medal && cur.winRate == null) next.medal = u.medal;
      if (u.hit7 != null) next.hit7 = u.hit7;
      if (u.calls30 != null) next.calls30 = u.calls30;
      if (u.median != null) next.median = u.median;
      out[key] = next;
    }
    const keys = Object.keys(out);
    if (keys.length > max) {
      keys.sort((a, b) => out[b].updatedAt - out[a].updatedAt);
      return Object.fromEntries(keys.slice(0, max).map((k) => [k, out[k]]));
    }
    return out;
  }

  // Links to a wallet page or a pool page carry addresses that are not coins.
  const stripNoise = (t) => String(t || '').replace(/https?:\/\/(?:www\.)?(?:solscan\.io|dexscreener\.com|birdeye\.so\/(?:profile|wallet))[^\s)>\]]*/gi, ' ');

  // Discord API message objects (content plus embeds, which alert bots use), oldest first.
  function fromDiscordMessages(messages) {
    const calls = [];
    for (const m of (messages || []).slice().sort((x, y) => snowflakeCmp(String(x.id), String(y.id)))) {
      const alert = parseAlert(m);
      if (alert) {
        // The bot that posts alerts is not the caller: credit the caller on the arrow line, and take only the real contract.
        const t = alert.trigger;
        calls.push({ address: alert.address, chain: alert.chain, poster: t ? t.caller : ((m.author && (m.author.global_name || m.author.username)) || 'unknown'), at: t ? t.ts : (Date.parse(m.timestamp) || 0), messageId: String(m.id), symbol: alert.symbol, name: alert.name, mcap: t && t.mcap ? t.mcap : alert.snap.fdv, group: t ? t.group : '', callerWin: t ? t.winRate : null, callerMedal: t ? t.medal : null, snap: alert.snap, first: alert.first ? { caller: alert.first.caller, ts: alert.first.ts, mcap: alert.first.mcap, group: alert.first.group } : null });
        continue;
      }
      const parts = [m.content];
      for (const e of m.embeds || []) { parts.push(e.title, e.description, e.url); for (const f of e.fields || []) parts.push(f.name, f.value); }
      const poster = (m.author && (m.author.global_name || m.author.username)) || 'unknown';
      const at = Date.parse(m.timestamp) || 0;
      const seen = new Set();
      for (const a of addressesIn(stripNoise(parts.filter(Boolean).join('\n')))) {
        if (seen.has(a.address)) continue;
        seen.add(a.address);
        calls.push(Object.assign(a, { poster, at, messageId: String(m.id) }));
      }
    }
    return calls;
  }

  // queue: { address: { address, chain, mentions, posters, firstPoster, firstAt, lastAt, ...research } }
  function addToQueue(queue, calls) {
    const q = Object.assign({}, queue);
    for (const c of calls || []) {
      const e = q[c.address] ? Object.assign({}, q[c.address], { posters: q[c.address].posters.slice(), channels: (q[c.address].channels || []).slice() }) : { address: c.address, chain: c.chain, mentions: 0, posters: [], channels: [], firstPoster: c.poster, firstAt: c.at, lastAt: c.at };
      e.mentions += 1;
      if (c.channel && !e.channels.includes(c.channel)) e.channels.push(c.channel);
      if (c.symbol && !e.symbol) e.symbol = c.symbol;
      if (c.snap && c.at >= (e.snapAt || 0)) { e.snap = c.snap; e.snapAt = c.at; }
      if (c.mcap && e.callMcap == null) e.callMcap = c.mcap;
      // The alert lists every earlier mention: the earliest one is the real first caller and the price they got.
      if (c.first && c.first.ts < e.firstAt) {
        e.firstAt = c.first.ts; e.firstPoster = c.first.caller; if (c.first.mcap) e.callMcap = c.first.mcap;
        if (!e.posters.includes(c.first.caller)) e.posters.push(c.first.caller);
      }
      if (!e.posters.includes(c.poster)) e.posters.push(c.poster);
      if (c.at < e.firstAt) { e.firstAt = c.at; e.firstPoster = c.poster; }
      if (c.at > e.lastAt) e.lastAt = c.at;
      q[c.address] = e;
    }
    return q;
  }

  const isFresh = (item, now, maxAgeMs) => item.launchedAt > 0 && now - item.launchedAt <= maxAgeMs;

  const VERDICT_ORDER = { 'Looks OK': 0, Caution: 1, 'High risk': 3, 'Walk away': 4 };
  const vRank = (v) => (v in VERDICT_ORDER ? VERDICT_ORDER[v] : 2);
  const rank = (items) => (items || []).slice().sort((a, b) => (vRank(a.verdict) - vRank(b.verdict)) || ((b.launchedAt || 0) - (a.launchedAt || 0)));

  // book: paper calls { poster, ret: { '1h' | '6h' | '24h': number | 'missed' } }
  function callerStats(book) {
    const by = new Map();
    for (const x of book || []) {
      if (!by.has(x.poster)) by.set(x.poster, []);
      by.get(x.poster).push(x);
    }
    const mark = (list, k) => { const rs = list.map((x) => (x.ret || {})[k]).filter((r) => typeof r === 'number'); return { n: rs.length, up: rs.filter((r) => r > 0).length, avg: rs.length ? rs.reduce((a, b) => a + b, 0) / rs.length : null }; };
    const rows = [...by.entries()].map(([poster, list]) => ({ poster, calls: list.length, h1: mark(list, '1h'), h6: mark(list, '6h'), h24: mark(list, '24h') }));
    const avg6 = (r) => (r.h6.avg == null ? -Infinity : r.h6.avg);
    return rows.sort((a, b) => (b.calls - a.calls) || (avg6(b) - avg6(a)) || a.poster.localeCompare(b.poster));
  }

  const api = { addressesIn, extractCalls, fromDiscordMessages, parseAlert, callerUpdates, applyCallerUpdates, addToQueue, isFresh, rank, callerStats, snowflakeCmp };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.Calls = api;
})(typeof window !== 'undefined' ? window : globalThis);

return module.exports; })();
const Feed = (function () { const module = { exports: {} }; 
// Discord feed Worker: pure storage and access helpers (no network). Tested in node, bundled for Cloudflare.
(function (root) {
  'use strict';
  const KEEP_MS = 3 * 86400000;
  const MAX_CALLS = 1000;
  const snowflakeCmp = (a, b) => (a.length - b.length) || (a < b ? -1 : a > b ? 1 : 0);

  const emptyStore = () => ({ calls: [], lastId: null, status: 'starting', checkedAt: 0 });

  // Add new calls, drop duplicates (same message and address) and anything older than 3 days, keep the newest 1000.
  // channelId: remember progress for that channel in lastIds (without it, the single lastId is used).
  function mergeStore(store, calls, messageIds, now, channelId) {
    const s = Object.assign(emptyStore(), store || {});
    const seen = new Set(s.calls.map((c) => c.messageId + '|' + c.address));
    const all = s.calls.slice();
    for (const c of calls || []) {
      const k = c.messageId + '|' + c.address;
      if (seen.has(k)) continue;
      seen.add(k);
      all.push(c);
    }
    const kept = all.filter((c) => now - c.at <= KEEP_MS).sort((a, b) => a.at - b.at);
    let lastId = channelId ? (s.lastIds || {})[channelId] : s.lastId;
    for (const id of messageIds || []) if (lastId == null || snowflakeCmp(String(id), String(lastId)) > 0) lastId = String(id);
    const out = Object.assign({}, s, { calls: kept.slice(-MAX_CALLS) });
    if (channelId) out.lastIds = Object.assign({}, s.lastIds, lastId == null ? {} : { [channelId]: lastId });
    else out.lastId = lastId;
    return out;
  }

  // "111:first scan, 222:price move, 333" -> [{ id, label }], digits-only ids, no repeats, at most 10.
  function parseChannels(text) {
    const out = [], seen = new Set();
    for (const part of String(text || '').split(',')) {
      const i = part.indexOf(':');
      const id = (i < 0 ? part : part.slice(0, i)).trim();
      if (!/^\d{3,25}$/.test(id) || seen.has(id)) continue;
      seen.add(id);
      out.push({ id, label: (i < 0 ? '' : part.slice(i + 1).trim()) || id });
      if (out.length >= 10) break;
    }
    return out;
  }

  // The worst of several channel states, so one bad channel is never hidden by the others being fine.
  const WORST = ['token_invalid', 'no_access', 'channel_not_found', 'discord_error', 'rate_limited', 'ok'];
  const rollup = (statuses) => { const list = (statuses || []).filter(Boolean); return list.length ? WORST.find((w) => list.includes(w)) || 'discord_error' : 'starting'; };

  const callsSince = (store, sinceMs) => ((store && store.calls) || []).filter((c) => c.at > sinceMs).sort((a, b) => a.at - b.at);

  const STATUS = { 200: 'ok', 401: 'token_invalid', 403: 'no_access', 404: 'channel_not_found', 429: 'rate_limited' };
  const statusFor = (code) => STATUS[code] || 'discord_error';

  // Constant-time compare so the key can't be guessed one character at a time.
  function authorized(given, feedKey) {
    if (!given || !feedKey || given.length !== feedKey.length) return false;
    let diff = 0;
    for (let i = 0; i < given.length; i++) diff |= given.charCodeAt(i) ^ feedKey.charCodeAt(i);
    return diff === 0;
  }

  function cors(origin, allowed) {
    const h = { 'Access-Control-Allow-Methods': 'GET, OPTIONS', 'Access-Control-Allow-Headers': 'x-feed-key', Vary: 'Origin' };
    if (origin && allowed && origin === allowed) h['Access-Control-Allow-Origin'] = allowed;
    return h;
  }

  // ---- GMGN read-only proxy: the five read endpoints the app uses, and only their parameters. Trading is never proxied. ----
  const GMGN_CHAINS = new Set(['sol', 'bsc', 'base', 'eth', 'arbitrum', 'hyperevm', 'robinhood', 'arc', 'stable']);
  const TOKEN_Q = ['chain', 'address', 'limit', 'order_by', 'direction', 'tag'];
  const GMGN_ENDPOINTS = {
    'token/info': { need: 'address', keys: ['chain', 'address'] },
    'token/security': { need: 'address', keys: ['chain', 'address'] },
    'market/token_top_holders': { need: 'address', keys: TOKEN_Q },
    'market/token_top_traders': { need: 'address', keys: TOKEN_Q },
    'user/created_tokens': { need: 'wallet_address', keys: ['chain', 'wallet_address', 'order_by', 'direction', 'migrate_state', 'limit'] },
  };
  function gmgnRequest(pathname, search) {
    const endpoint = String(pathname || '').replace(/^\/gmgn\//, '');
    const spec = Object.prototype.hasOwnProperty.call(GMGN_ENDPOINTS, endpoint) ? GMGN_ENDPOINTS[endpoint] : null;
    if (!spec) return null;
    const params = {};
    for (const k of spec.keys) { const v = search.get(k); if (v != null && v !== '') params[k] = v; }
    if (!GMGN_CHAINS.has(params.chain)) return null;
    if (!/^[A-Za-z0-9]{20,64}$/.test(params[spec.need] || '')) return null;
    for (const k of Object.keys(params)) if (k !== spec.need && k !== 'chain' && !/^[a-z0-9_]{1,30}$/.test(params[k])) return null;
    return { endpoint, params };
  }
  const gmgnUrl = (endpoint, params, nowSec, clientId) => `https://openapi.gmgn.ai/v1/${endpoint}?${new URLSearchParams(Object.assign({}, params, { timestamp: String(nowSec), client_id: clientId }))}`;

  const api = { emptyStore, mergeStore, callsSince, statusFor, authorized, cors, parseChannels, rollup, gmgnRequest, gmgnUrl, KEEP_MS, MAX_CALLS };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.FeedCore = api;
})(typeof window !== 'undefined' ? window : globalThis);

return module.exports; })();
// Discord feed Worker. When the app asks GET /calls?since=<ms> (with the feed key) it reads new messages in each listed channel
// (read-only, with the token stored as a Cloudflare secret), catches up on anything missed, and keeps the contract addresses it finds.

const KEY = 'store3'; // a new key drops stored calls that were read before the parser ignored wallet and pool links

async function load(env) {
  const raw = await env.CALLS.get(KEY);
  try { return raw ? JSON.parse(raw) : Feed.emptyStore(); } catch (e) { return Feed.emptyStore(); }
}

async function loadCallers(env) {
  const raw = await env.CALLS.get('callers');
  try { return raw ? JSON.parse(raw) : {}; } catch (e) { return {}; }
}

// Mark the profiles that changed so the app can ask for only those.
function touch(before, after, now) {
  const out = {};
  for (const k of Object.keys(after)) out[k] = after[k] === before[k] ? after[k] : Object.assign({}, after[k], { touched: now });
  return out;
}

const MAX_PAGES = 10;        // pages of 50 messages per channel and request (500 messages)
const PAGE = 50;
const lastRun = new WeakMap(); // this Worker instance's last read, per storage binding

// Read every listed channel (read-only), paging forward through anything missed. Saves only when something changed.
async function poll(env) {
  const channels = Feed.parseChannels(env.CHANNEL_ID);
  let store = await load(env);
  // Progress saved by the single-channel version belongs to the first channel listed.
  if (store.lastId && !store.lastIds && channels[0]) store = Object.assign({}, store, { lastIds: { [channels[0].id]: store.lastId } });
  const before = store;
  const now = Date.now();
  let callers = await loadCallers(env);
  const callersBefore = callers;
  const statuses = {};
  let stop = false;
  for (const ch of channels) {
    if (stop) { statuses[ch.id] = 'token_invalid'; continue; }
    try {
      for (let page = 0; page < MAX_PAGES; page++) {
        let url = `https://discord.com/api/v10/channels/${ch.id}/messages?limit=${PAGE}`;
        const last = (store.lastIds || {})[ch.id];
        if (last) url += `&after=${last}`;
        const r = await fetch(url, { method: 'GET', headers: { Authorization: env.DISCORD_TOKEN } });
        const status = Feed.statusFor(r.status);
        statuses[ch.id] = status;
        if (status !== 'ok') { if (status === 'token_invalid') stop = true; break; } // a rejected token fails everywhere; don't keep asking
        const messages = await r.json();
        const list = Array.isArray(messages) ? messages : [];
        if (!list.length) break;
        const calls = Calls.fromDiscordMessages(list).map((c) => Object.assign(c, { channel: ch.label }));
        store = Feed.mergeStore(store, calls, list.map((m) => String(m.id)), now, ch.id);
        callers = touch(callers, Calls.applyCallerUpdates(callers, Calls.callerUpdates(list)), now);
        // The very first read takes only the latest messages; after that a full page means there may be more.
        if (!last || list.length < PAGE) break;
      }
    } catch (e) {
      statuses[ch.id] = 'discord_error';
    }
  }
  const state = { status: Feed.rollup(channels.map((c) => statuses[c.id])), channels: channels.map((c) => ({ id: c.id, label: c.label, status: statuses[c.id] })) };
  const next = Object.assign({}, store, state, { checkedAt: now });
  const changed = store !== before || JSON.stringify(state) !== JSON.stringify({ status: before.status, channels: before.channels }) || !before.checkedAt;
  if (changed) await env.CALLS.put(KEY, JSON.stringify(next));
  if (callers !== callersBefore) await env.CALLS.put('callers', JSON.stringify(callers));
  return { store: next, callers };
}

// Read Discord for this request unless this instance read it moments ago (or force: the schedule, if you add one).
async function refresh(env, force) {
  const gap = env.MIN_GAP_MS === undefined ? 30000 : Number(env.MIN_GAP_MS) || 0;
  const last = lastRun.get(env.CALLS) || 0;
  if (!force && Date.now() - last < gap) return null;
  lastRun.set(env.CALLS, Date.now());
  try { return await poll(env); } catch (e) { return null; }
}

// ---- GMGN read-only proxy (the key stays here as a Worker secret) ----
const GMGN_TTL = 5 * 60000;
const gmgnCache = new Map(); // request -> { at, body }
let gmgnPausedUntil = 0;

async function gmgn(url, env, headers) {
  if (!env.GMGN_API_KEY) return json({ error: 'not_configured' }, 503, headers);
  const req = Feed.gmgnRequest(url.pathname, url.searchParams);
  if (!req) return json({ error: 'not_allowed' }, 400, headers);
  const now = Date.now();
  if (now < gmgnPausedUntil) return json({ error: 'rate_limited', retryAt: gmgnPausedUntil }, 429, headers);
  const key = req.endpoint + '?' + new URLSearchParams(req.params);
  const hit = gmgnCache.get(key);
  if (hit && now - hit.at < GMGN_TTL) return json(hit.body, 200, headers);
  let r, j;
  try {
    r = await fetch(Feed.gmgnUrl(req.endpoint, req.params, Math.floor(now / 1000), crypto.randomUUID()), { headers: { 'X-APIKEY': env.GMGN_API_KEY, 'User-Agent': 'fomo-tracker-worker' } });
    j = await r.json().catch(() => null);
  } catch (e) {
    return json({ error: 'gmgn_unreachable' }, 502, headers);
  }
  // GMGN lengthens a ban when it keeps being asked during one, so stop asking for a minute.
  if (r.status === 429) { gmgnPausedUntil = now + 60000; return json({ error: 'rate_limited', retryAt: gmgnPausedUntil }, 429, headers); }
  if (!r.ok || !j || (j.code !== undefined && j.code !== 0)) return json({ error: (j && (j.message || j.msg)) || 'gmgn_http_' + r.status }, 502, headers);
  const body = { data: j.data !== undefined ? j.data : j };
  gmgnCache.set(key, { at: now, body });
  if (gmgnCache.size > 300) gmgnCache.delete(gmgnCache.keys().next().value);
  return json(body, 200, headers);
}

function json(body, status, headers) {
  return new Response(JSON.stringify(body), { status, headers: Object.assign({ 'Content-Type': 'application/json', 'Cache-Control': 'no-store' }, headers) });
}

export default {
  // Optional: a Cron Trigger works too, but it reads around the clock and uses up the free storage writes.
  async scheduled(event, env, ctx) {
    ctx.waitUntil(refresh(env, true));
  },
  async fetch(request, env) {
    const headers = Feed.cors(request.headers.get('Origin'), env.ALLOWED_ORIGIN);
    if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers });
    const url = new URL(request.url);
    const isGmgn = url.pathname.startsWith('/gmgn/');
    if (request.method !== 'GET' || (url.pathname !== '/calls' && !isGmgn)) return json({ error: 'not_found' }, 404, headers);
    if (!Feed.authorized(request.headers.get('x-feed-key') || '', env.FEED_KEY || '')) return json({ error: 'unauthorized' }, 401, headers);
    if (isGmgn) return gmgn(url, env, headers);
    const polled = await refresh(env, false);
    const store = polled ? polled.store : await load(env);
    const since = Number(url.searchParams.get('since')) || 0;
    const csince = Number(url.searchParams.get('csince')) || 0;
    const callers = polled ? polled.callers : await loadCallers(env);
    const changed = {};
    for (const k of Object.keys(callers)) if ((callers[k].touched || 0) > csince) changed[k] = callers[k];
    return json({ status: store.status, checkedAt: store.checkedAt, now: Date.now(), channels: store.channels || [], calls: Feed.callsSince(store, since), callers: changed }, 200, headers);
  },
};
